--- #YAML:1.0
name:                MyCPAN-Indexer
version:             0.10_02
abstract:            Index a Perl distribution
license:             perl
author:              
    - brian d foy <bdfoy@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Archive::Extract:              0
    Distribution::Guess::BuildSystem: 0
    Log::Log4perl:                 0
    MD5:                           0
    Module::Extract::Namespaces:   0
    Module::Extract::Version:      0
    Test::More:                    0
    YAML::Syck:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
